ProgramNexus/urls.py
from django.contrib import admin
from django.urls import include, path
import core
import resource

urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include("core.urls")),
    path('',include("resource.urls"))
]

as8_db/urls.py
from django.contrib import admin
from django.urls import include, path
import core

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls"))
]

core/urls.py
# Importing necessary modules & libraries
from django.urls import path
from core import views


# Setting the app_name and url paths
app_name = "core"
urlpatterns = [
    path('', views.index, name="index"),
    path('analytics', views.analytics, name="analytics"),
    path('user_login', views.user_login, name="user_login"),
    path('user_logout', views.user_logout, name="user_logout"),
    path('download_BUF', views.download_BUF, name="download_BUF")
]

core/models.py
# Importing necessary modules & libraries
import uuid
from django.db import models
from django.contrib.auth.models import User


# Creating Django Models. Each represent a table.
class UserAdditionalInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # additional
    github_profile = models.URLField(null=True, blank=True)
    discord_username = models.CharField(max_length=100, null=True, blank=True)
    social_link = models.URLField(null=True, blank=True)
    org_task = models.CharField(max_length=100, null=False, blank=False)


    def __str__(self):
        return self.user.username


class Tag(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, null=False, blank=False)
    value = models.CharField(max_length=50, null=False, blank=False, unique=True)

    def __str__(self):
        return f"{self.value}"
    
    def save(self, *args, **kwargs):
        self.value = self.value.lower()
        return super(Tag, self).save(*args, **kwargs)


class Organization(models.Model):
    ORGANIZATION_POPULARITY = [
        ('High','High'),
        ('Mid','Mid'),
        ('Low','Low')
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, null=False, blank=False)
    name = models.CharField(max_length=100, null=False, blank=False, unique=True)
    email = models.EmailField(unique=True, null=True, blank=True)
    site = models.URLField(unique=True, null=True, blank=True)
    location = models.CharField(max_length=200, null=False, blank=False)
    is_club = models.BooleanField(null=False, blank=False)
    institution = models.CharField(max_length=100, null=True, blank=True)
    popularity = models.CharField(max_length=4, choices=ORGANIZATION_POPULARITY, default='Mid', null=False, blank=False)
    is_active = models.BooleanField(null=False, blank=False)
    related_tag = models.ManyToManyField(Tag, related_name="org_tag", blank=True)

    def __str__(self):
        return f"{self.name} • {self.popularity}"

    def save(self, *args, **kwargs):
        self.location = self.location.title()
        if self.institution != None:
            self.institution = self.institution.title()
        return super(Organization, self).save(*args, **kwargs)


class Initiative(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, null=False, blank=False)
    name = models.CharField(max_length=100, null=False, blank=False, unique=True)
    date = models.DateField(null=True, blank=True)
    site = models.URLField(null=True, blank=True)
    parent_org = models.ForeignKey(Organization, on_delete=models.PROTECT, related_name="initiative_org", null=True, blank=True)
    related_tag = models.ManyToManyField(Tag, related_name="initiative_tag", blank=True)

    def __str__(self):
        return f"{self.name}"


class Resource(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, null=False, blank=False)
    name = models.CharField(max_length=100, null=False, blank=False)
    description = models.TextField(null=False, blank=False)
    date = models.DateField(null=True, blank=True)
    link = models.URLField(null=False, blank=False)
    parent_org = models.ForeignKey(Organization, on_delete=models.PROTECT, related_name="post_org", null=True, blank=True)
    followed_initiative = models.ManyToManyField(Initiative, related_name="resource_initiative", blank=True)
    can_display = models.BooleanField(null=False, blank=False)
    related_tag = models.ManyToManyField(Tag, related_name="resource_tag", blank=True)

    def __str__(self):
        return f"{self.name} • {self.parent_org.name}"


class Consumer(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, null=False, blank=False)
    name = models.CharField(max_length=100, null=False, blank=False)
    email = models.EmailField(unique=True, null=True, blank=True)
    age = models.IntegerField(null=False, blank=False)
    location = models.CharField(max_length=200, null=False, blank=False)
    profession = models.CharField(max_length=200, null=False, blank=False)
    institution = models.CharField(max_length=200, null=False, blank=False)
    social_link = models.URLField(null=True, blank=True)
    initiative_part = models.ManyToManyField(Initiative, related_name="consumer_initiative", blank=True)
    send_newsletter = models.BooleanField(null=False, blank=False)

    def __str__(self):
        return f"{self.name}"

    def save(self, *args, **kwargs):
        self.name = self.name.title()
        self.location = self.location.title()
        self.profession = self.profession.lower()
        self.institution = self.institution.title()
        return super(Consumer, self).save(*args, **kwargs)

core/forms.py
# Importing necessary modules & libraries
from django import forms


# A simple LoginForm
class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100, widget=forms.PasswordInput)

core/views.py
# Importing necessary modules & libraries
from django.shortcuts import render
from core.forms import LoginForm

from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from core import backup
from core import analytics as module_analytics



# Creating Django Views.
# Each URL Paths will be connected to a Django View and 
# Each Django View will be connected to a html file
def index(request):
    return render(request, "core/index.html")


def user_login(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('core:index'))
            else:
                return render(request, 'core/login_error.html', {"headline": "Account Not Active!"})
        
        else:
            return render(request, 'core/login_error.html', {"headline": "Invalid Login Details Supplied!"})
    
    else:
        return render(request, 'core/user_login.html', {
            'login_form': LoginForm()
        })


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("core:index"))


@login_required
def analytics(request):
    module_analytics.main()
    return render(request, "core/analytics.html")


@login_required
def download_BUF(request):
    zip_file = open("BUF.zip", "rb")
    response = HttpResponse(zip_file, content_type="application/force-download")
    response["Content-Disposition"] = f"attachment; filename=BUF.zip"
    return response

core/templates/core/analytics.html
{% extends 'core/base.html' %}
{% load static %}

{% comment %}
    This is the analytics.html file. 
    This file will inherit the basic structure from base.html file.
    Here you will find some graphs & charts 
    which will represent the analytics of the AS8 Org Database.
    You can't access this file without log in.
{% endcomment %}

{% block body %}
    <div class="container">
        <section id="hero">
            <div class="hero-title">
                <h1 class="main-title">Welcome to <br> AS8 ORG <span class="change-color">Database</span> <br>Analytics</h1>
                <a href="{% url 'core:download_BUF' %}"><button type="button" class="btn btn-primary btn-light" id="hero-btn">Download BackUp Files</button></a>
            </div>
            <div class="hero-image">
                <img id="hi-special" src="{% static 'core/images/analytics-graphics.svg' %}" alt="main-graphics">
            </div>
        </section>
    </div>

    <section id="analytics-details">
        <div class="analytics-tables">
            <div class="container">
                <h1 class="section-head">Organization<span class="change-color">Analytics</span>.</h1>
                <img class="analytics-img" src="{% static 'core/images/plots/plot1.png' %}">
                <img class="analytics-img" src="{% static 'core/images/plots/plot2.png' %}">
                <img class="analytics-img" src="{% static 'core/images/plots/plot3.png' %}">
                <img class="analytics-img" src="{% static 'core/images/plots/plot4.png' %}">
                <img class="analytics-img" src="{% static 'core/images/plots/plot5.png' %}">
                <img class="analytics-img" src="{% static 'core/images/plots/plot6.png' %}">
            </div>
        </div>

        <div class="analytics-tables">
            <div class="container">
                <h1 class="section-head">Consumer<span class="change-color">Analytics</span>.</h1>
                <img class="analytics-img" src="{% static 'core/images/plots/plot7.png' %}">
                <img class="analytics-img" src="{% static 'core/images/plots/plot8.png' %}">
                <img class="analytics-img" src="{% static 'core/images/plots/plot9.png' %}">
                <img class="analytics-img" src="{% static 'core/images/plots/plot10.png' %}">
                <img class="analytics-img" src="{% static 'core/images/plots/plot11.png' %}">
            </div>
        </div>
    </section>

{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>
{% load static %}

{% comment %}
    This is the base html file. 
    It contains basic structure such as header, navbar, footer etc. 
    All other html files will inherit this basic structure.
{% endcomment %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AS8 ORG | DB</title>
    <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.7/css/all.css">


    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'core/images/favicon/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'core/images/favicon/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'core/images/favicon/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'core/images/favicon/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'core/images/favicon/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'core/images/favicon/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'core/images/favicon/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'core/images/favicon/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'core/images/favicon/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'core/images/favicon/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'core/images/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'core/images/favicon/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'core/images/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'core/images/favicon/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'core/images/favicon/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">

</head>

<body>
    <header>
        <nav id="main-nav" class="navbar navbar-expand-lg navbar-light">
            <div class="container">
                <a class="navbar-brand" href="{% url 'core:index' %}">
                    <img src="{% static 'core/images/brand-logo.png' %}" alt="" class="d-inline-block align-text-top">
                </a>
                <button class="navbar-toggler" style="background-color:white;" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" target="_blank" href="https://the-as8-organization.github.io/">Main</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:analytics' %}">Analytics</a>
                        </li>

                        {% if user.is_authenticated %}
                            <li class="nav-item off">
                                <a href="{% url 'core:user_logout' %}"><button type="button" class="btn btn-primary btn-light">Log out</button></a>
                            </li>
                        {% else %}
                            <li class="nav-item off">
                                <a href="{% url 'core:user_login' %}"><button type="button" class="btn btn-primary btn-light">Log in</button></a>
                            </li>
                        {% endif %}

                    </ul>
                </div>
                {% if user.is_authenticated %}
                    <a href="{% url 'core:user_logout' %}"><button type="button" class="btn btn-primary btn-light on">Log out</button></a>
                {% else %}
                    <a href="{% url 'core:user_login' %}"><button type="button" class="btn btn-primary btn-light on">Log in</button></a>
                {% endif %}
            </div>
        </nav>
    </header>

    {% block body %}
    {% endblock %}



    <footer>
        <div class="container">
            <ul id="social">
                <li><a id="first" href="https://www.facebook.com/as8org/" target="_blank"><i class="social-bicon fab fa-facebook"></i></a></li>
                <li><a href="https://www.instagram.com/as8org/" target="_blank"><i class="social-bicon fab fa-instagram"></i></a></li>
                <li><a href="https://www.linkedin.com/company/the-as8-organization" target="_blank"><i class="social-bicon fab fa-linkedin-in"></i></a></li>
                <li><a href="https://www.youtube.com/channel/UCjcS_VOSsg3ju2rwKZVNUnQ" target="_blank"><i class="social-bicon fab fa-youtube"></i></a></li>
                <li><a href="https://github.com/The-AS8-organization" target="_blank"><i class="social-bicon fab fa-github"></i></a></li>
            </ul>
            <h2 id="org-name">Created by <a class="under-link" href="http://ahammadshawki8.github.io/" target="_blank">Ahammad Shawki</a></h2>

            <div id="license">
                <h2 id="copyright">Copyright &copy; AS8 ORG Database Application <script>
                    document.write(new Date().getFullYear());
                </script></h2>
                <h2 id="allright">All rights reserved</h2>
            </div>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
        integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
        integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc"
        crossorigin="anonymous"></script>
</body>

</html>

core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% comment %}
    This is the index.html file. 
    This file will inherit the basic structure from base.html file.
    This represents the home page of the entire application.
    Here you will find a simple & short detail about this application.
{% endcomment %}


{% block body %}
<div class="container">
    <section id="hero">
        <div class="hero-title">
            <h1 class="main-title">Easier <br> Database Management <br> & <span class="change-color">Analytical</span>
                Support</h1>

        </div>
        <div class="hero-image">
            <img src="{% static 'core/images/main-graphics.svg' %}" alt="main-graphics">
        </div>
    </section>
</div>

<section id="application-details">
    <div class="container">
        <h1 class="section-head">Application<span class="change-color">Details</span>.</h1>
        <p class="lead">Maintaining a resourceful database is nowadays crucial for the development of an organization.
            But only database management isn't sufficient for that purpose. We need to represent them with proper
            analytics. There is so much going on in the background of such operations. That's why The AS8 Organization took the
            initiative of creating a database management application that will help them to achieve their goals. This
            database application is mainly built with Python's Django framework and SQLite database. Please help us to
            make this application accurate by <a class="under-link" href="https://github.com/The-AS8-organization/AS8-ORG-Database-Application/issues/new/choose" target="_blank">reporting bugs</a>.</p>
    </div>
</section>

{% endblock %}

core/templates/core/login_error.html
{% extends 'core/base.html' %}
{% load static %}

{% comment %}
    This is the login_error.html file. 
    This file will inherit the basic structure from base.html file.
    This will appear if there is any mistake made by the user in the login form.
{% endcomment %}


{% block body %}
<div class="container">
    <section id="hero">
        <div class="hero-title">
            <h1 class="main-title">{{ headline }}</span></h1>
        </div>
        <div class="hero-image">
            <img id="hi-special" src="{% static 'core/images/error-graphics.svg' %}" alt="main-graphics">
        </div>
    </section>
</div>

{% endblock %}

core/templates/core/user_login.html
<!DOCTYPE html>
{% extends "core/base.html" %}

{% comment %}
    This is the user_login.html file. 
    This file will inherit the basic structure from base.html file.
    Here you will find a simple login form.
{% endcomment %}

{% block body %}
<div class="login-form">
    <h1 class="section-head">Please<span class="change-color">Login</span>.</h1>
    <form action="{% url 'core:user_login' %}" method="post">
        {% csrf_token %}
        {{ login_form.as_p }}
        <input type="submit" value="Submit">
    </form>
</div>
{% endblock %}